
package com.project.GUI;

import com.project.DTO.*;
import com.project.BUS.*;

import java.awt.Cursor;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

public class DetailWareHouse extends javax.swing.JFrame {
    private PermissionAccount permissionList;
    WareHouseService wareHouseService;
    WareHouse warehouse;

    public DetailWareHouse(int idWareHouse) {
        initComponents();
        permissionList = PermissionAccount.getInstance();
        wareHouseService = new WareHouseService();
        try {
            warehouse = wareHouseService.getIdWareHouse(idWareHouse);
            jtfCode.setText(String.valueOf(warehouse.getId()));
            jtfCode.setEnabled(false);
            jtfName.setText(warehouse.getName());
            Timestamp timestamp = warehouse.getCreateDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String formattedDateTime = dateFormat.format(timestamp);
            jtfCreate.setText(formattedDateTime);
            jtfCreate.setEnabled(false);
            Timestamp updateTime = warehouse.getUpdateDate();
            String formatUpdate = dateFormat.format(updateTime);
            jtfUpdate.setText(formatUpdate);
            jtfUpdate.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(DetailWareHouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setResizable(false);
        jPanel1 = new javax.swing.JPanel();
        jlbCode = new javax.swing.JLabel();
        jtfCode = new javax.swing.JTextField();
        jlbName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jlbCreate = new javax.swing.JLabel();
        jtfCreate = new javax.swing.JTextField();
        jbUpdate = new javax.swing.JButton();
        jlbCreate1 = new javax.swing.JLabel();
        jtfUpdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nguyên liệu",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jlbCode.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jlbCode.setText("Mã Nguyên Liệu");

        jtfCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodeActionPerformed(evt);
            }
        });

        jlbName.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jlbName.setText("Tên Nguyên Liệu");

        jtfName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });

        jlbCreate.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jlbCreate.setText("Ngày Tạo");

        jtfCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfCreate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCreateActionPerformed(evt);
            }
        });

        jbUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbUpdate.setText("Cập nhật");
        jbUpdate.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        jlbCreate1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jlbCreate1.setText("Cập nhật gần đây");

        jtfUpdate.setEnabled(false);
        jtfUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfUpdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jlbCode, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlbName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jtfCode,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 96,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        26, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jbUpdate)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jtfCreate,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        225,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jtfName,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        225,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jtfUpdate,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        225,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(43, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jlbCreate1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 152,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlbCreate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlbCode, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfCode, javax.swing.GroupLayout.DEFAULT_SIZE, 33,
                                                Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 33,
                                                Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbCreate, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 33,
                                                Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbCreate1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 33,
                                                Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfCodeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfCodeActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNameActionPerformed

    private void jtfCreateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfCreateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfCreateActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbUpdateActionPerformed
        if (permissionList.hasPermission("UPDATE_WAREHOUSE")) {
                warehouse.setName(jtfName.getText());
                try {
                    if(wareHouseService.WareHouseExist(warehouse.getName()))
                    {
                            JOptionPane.showMessageDialog(null, "Tên nguyên liệu '" + warehouse.getName() + "'  đã tồn tại. Không thể chỉnh sửa nguyên liệu này.");
                            jtfName.requestFocus();
                            return;
                    }
                    else 
                    {
                            wareHouseService.updateNameWareHouse(warehouse);
                            JOptionPane.showMessageDialog(null, "Cập nhật nguyên liệu thành công");
                            this.dispose();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(DetailWareHouse.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập");
                return;
            }
    }// GEN-LAST:event_jbUpdateActionPerformed

    private void jtfUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfUpdateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JLabel jlbCode;
    private javax.swing.JLabel jlbCreate;
    private javax.swing.JLabel jlbCreate1;
    private javax.swing.JLabel jlbName;
    private javax.swing.JTextField jtfCode;
    private javax.swing.JTextField jtfCreate;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfUpdate;
    // End of variables declaration//GEN-END:variables
}
