package com.project.GUI;

import java.awt.Cursor;
import java.util.Formatter;

import javax.swing.JOptionPane;

import com.project.BUS.AccountBUS;
import com.project.Common.Authen;
import com.project.Common.Common;
import com.project.Common.PasswordHasher;
import com.project.DTO.AccountDTO;
import com.project.DTO.PermissionAccount;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thuan
 */
public class DetailAccountForm extends javax.swing.JFrame {
    private AccountDTO dataAccountDTO;
    private PermissionAccount permissionList;

    /**
     * Creates new form DetailProduct
     */
    public DetailAccountForm(AccountDTO data) {
        permissionList = PermissionAccount.getInstance();
        initComponents();
        dataAccountDTO = data;
        loadData(data);
    }

    private void loadData(AccountDTO account) {
        jTextField1.setText(String.valueOf(account.getId()));
        jTextField2.setText(String.valueOf(account.getEmail()));
        jComboBox1.setSelectedItem(account.getRole());
        jTextField3.setText(Common.formatedDateTime(account.getCreatedAt()));
        jTextField4.setText(Common.formatedDateTime(account.getUpdatedAt()));
        jPasswordField1.setText(String.valueOf(account.getPassword()));

        jPasswordField1.setEnabled(false);
        jTextField1.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setResizable(false);
        jPanel1 = new javax.swing.JPanel();
        titleForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JToggleButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        BtnUpdate = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();

        setTitle("Chi tiết tài khoản");
        setMinimumSize(new java.awt.Dimension(730, 528));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        titleForm.setBackground(new java.awt.Color(255, 153, 102));
        titleForm.setForeground(new java.awt.Color(255, 255, 255));
        titleForm.setPreferredSize(new java.awt.Dimension(602, 30));
        titleForm.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chi tiết tài khoản");
        titleForm.add(jLabel1, "card2");

        jPanel1.add(titleForm, java.awt.BorderLayout.PAGE_START);

        jPanel3.setMinimumSize(new java.awt.Dimension(730, 408));
        jPanel3.setPreferredSize(new java.awt.Dimension(730, 408));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 25));

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã tài khoản");
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel5.add(jLabel2, java.awt.BorderLayout.LINE_START);
        jPanel5.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(320, 40));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Email");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 17));
        jPanel6.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel6.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ngày tạo");
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel7.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel7.add(jTextField3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(320, 40));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Quyền");
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 17));
        jPanel8.add(jLabel5, java.awt.BorderLayout.LINE_START);

        if (permissionList.getRoleId() == 1) {
            jComboBox1.setModel(
                    new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Staff" }));
        } else {
            jComboBox1.setModel(
                    new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Staff" }));

        }

        jPanel8.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setMinimumSize(new java.awt.Dimension(220, 22));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Cập nhật cuối");
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel9.add(jLabel6, java.awt.BorderLayout.LINE_START);
        jPanel9.add(jTextField4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        jPanel13.setMinimumSize(new java.awt.Dimension(220, 22));
        jPanel13.setPreferredSize(new java.awt.Dimension(450, 40));
        jPanel13.setRequestFocusEnabled(false);
        jPanel13.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Mật khẩu");
        jLabel10.setName(""); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel13.add(jLabel10, java.awt.BorderLayout.LINE_START);

        btnResetPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnResetPassword.setText("Cập lại mật khẩu");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });
        jPanel13.add(btnResetPassword, java.awt.BorderLayout.LINE_END);

        jPasswordField1.setText("jPasswordField1");
        jPanel13.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel13);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(728, 50));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 30, 0));

        BtnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnUpdate.setText("Cập nhật");
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setBackground(new java.awt.Color(0, 191, 255));
        BtnUpdate.setCursor(new Cursor(Cursor.HAND_CURSOR));

        BtnUpdate.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(BtnUpdate);

        BtnClose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnClose.setText("Đóng");
        BtnClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BtnClose.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnClose.setForeground(new java.awt.Color(255, 255, 255));
        BtnClose.setBackground(java.awt.Color.RED);
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(BtnClose);
        jPanel2.setBackground(java.awt.Color.WHITE);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {

        if ("Manager".equals(permissionList.getRoleName())) {
            if (dataAccountDTO.getRole().equals("Admin")) {
                JOptionPane.showMessageDialog(null, "Bạn không thể chỉnh sửa tài khoản có quyền cao hơn.");
                return;
            }
        }

        int id = Integer.parseInt(jTextField1.getText());
        String email = jTextField2.getText();
        int role_id = jComboBox1.getSelectedIndex();
        char[] passwordChars = jPasswordField1.getPassword();
        String password = new String(passwordChars);

        if (!Authen.validateEmail(email)) {
            return;
        }

        boolean check = AccountBUS.updateUserBUS(new AccountDTO(id, email, password, role_id + 1));

        if (check) {
            JOptionPane.showMessageDialog(null, "Cập nhật thông tin tài khoản thành công.");
            this.setVisible(false);
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật thông tin tài khoản thất bại.");
            return;

        }

    }

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {

        if ("Manager".equals(permissionList.getRoleName())) {
            if (dataAccountDTO.getRole().equals("Admin")) {
                JOptionPane.showMessageDialog(null, "Bạn không thể chỉnh sửa tài khoản có quyền cao hơn.");
                return;
            }
        }

        int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn đặt lại mật khẩu?", getTitle(),
                JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Mật khẩu mới là: password123");
            String hashNewPassword = PasswordHasher.hashPassword("password123");
            jPasswordField1.setText(hashNewPassword);
        } else {
            return;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailAccountForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailAccountForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailAccountForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailAccountForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new DetailAccountForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JToggleButton btnResetPassword;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel titleForm;
    // End of variables declaration
}
