/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.GUI;

import javax.swing.JOptionPane;

import com.project.BUS.AccountBUS;
import com.project.Common.Authen;
import com.project.DAO.AccountDAO;
import com.project.DTO.AccountDTO;

/**
 *
 * @author admin
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        login = new javax.swing.JPanel();
        title_signUp1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        main_signUp1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        btn_signUp1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        label_chuaCoTK = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        title_signUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main_signUp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_signUp = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        label_daCoTK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(new java.awt.FlowLayout());

        login.setMaximumSize(null);
        login.setOpaque(false);
        login.setPreferredSize(new java.awt.Dimension(600, 350));
        login.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        title_signUp1.setLayout(new java.awt.CardLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("./src/assets/icon/add(1).png")); // NOI18N
        jLabel6.setText("Đăng nhập");
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 25));
        title_signUp1.add(jLabel6, "card2");

        login.add(title_signUp1);

        main_signUp1.setMinimumSize(new java.awt.Dimension(400, 96));
        main_signUp1.setPreferredSize(new java.awt.Dimension(400, 150));
        main_signUp1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jPanel6.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("./src/assets/icon/mail(1).png")); // NOI18N
        jLabel7.setText("Email");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel6.add(jLabel7);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField2);

        main_signUp1.add(jPanel6);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("./src/assets/icon/padlock.png")); // NOI18N
        jLabel10.setText("Mật khẩu");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel11.add(jLabel10);

        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel11.add(jTextField6);

        main_signUp1.add(jPanel11);

        login.add(main_signUp1);

        jPanel12.setPreferredSize(new java.awt.Dimension(400, 31));
        jPanel12.setLayout(new java.awt.CardLayout());

        btn_signUp1.setBackground(new java.awt.Color(102, 204, 255));
        btn_signUp1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_signUp1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/profile.png")); // NOI18N
        btn_signUp1.setText("Đăng nhập");
        btn_signUp1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_signUp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signUp1MouseClicked(evt);

            }
        });
        jPanel12.add(btn_signUp1, "card2");

        login.add(jPanel12);

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel9.setLayout(new java.awt.CardLayout());

        label_chuaCoTK.setForeground(new java.awt.Color(102, 204, 255));
        label_chuaCoTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_chuaCoTK.setText("Bạn chưa có tài khoản?");
        label_chuaCoTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_chuaCoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_chuaCoTKMouseClicked(evt);
            }
        });
        jPanel9.add(label_chuaCoTK, "card2");

        login.add(jPanel9);

        getContentPane().add(login);

        signup.setMaximumSize(null);
        signup.setOpaque(false);
        signup.setPreferredSize(new java.awt.Dimension(600, 350));
        signup.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        title_signUp.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/add(1).png")); // NOI18N
        jLabel1.setText("Đăng ký");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 25));
        title_signUp.add(jLabel1, "card2");

        signup.add(title_signUp);

        main_signUp.setMinimumSize(new java.awt.Dimension(400, 96));
        main_signUp.setPreferredSize(new java.awt.Dimension(400, 150));
        main_signUp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setIcon(new javax.swing.ImageIcon("./src/assets/icon/mail(1).png")); // NOI18N
        jLabel2.setText("Email");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel2.add(jLabel2);
        jPanel2.add(jTextField1);

        main_signUp.add(jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon("./src/assets/icon/padlock.png")); // NOI18N
        jLabel3.setText("Mật khẩu");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel3);
        jPanel4.add(jPasswordField1);

        main_signUp.add(jPanel4);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setIcon(new javax.swing.ImageIcon("./src/assets/icon/id-card(1).png")); // NOI18N
        jLabel4.setText("Họ và tên");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel1.add(jLabel4);
        jPanel1.add(jTextField3);

        main_signUp.add(jPanel1);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jLabel5.setIcon(new javax.swing.ImageIcon("./src/assets/icon/call.png")); // NOI18N
        jLabel5.setText("Số điện thoại");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel5);
        jPanel5.add(jTextField4);

        main_signUp.add(jPanel5);

        signup.add(main_signUp);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 31));
        jPanel3.setLayout(new java.awt.CardLayout());

        btn_signUp.setBackground(new java.awt.Color(102, 204, 255));
        btn_signUp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_signUp.setIcon(new javax.swing.ImageIcon("./src/assets/icon/add-friend.png")); // NOI18N
        btn_signUp.setText("ĐĂNG KÝ");
        btn_signUp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signUpMouseClicked(evt);
            }
        });
        jPanel3.add(btn_signUp, "card2");

        signup.add(jPanel3);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel10.setLayout(new java.awt.CardLayout());

        label_daCoTK.setForeground(new java.awt.Color(102, 204, 255));
        label_daCoTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_daCoTK.setText("Bạn đã có tài khoản?");
        label_daCoTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_daCoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_daCoTKMouseClicked(evt);
            }
        });
        jPanel10.add(label_daCoTK, "card2");

        signup.add(jPanel10);

        getContentPane().add(signup);

        pack();
    }// </editor-fold>                        

    private void label_chuaCoTKMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        login.setVisible(false);
        signup.setVisible(true);
        
    }                                           

    private void label_daCoTKMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        login.setVisible(true);
        signup.setVisible(false);
    }  
    private void btn_signUpMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        String email=jTextField1.getText();
        char[] pass=jPasswordField1.getPassword();
        String password= new String(pass);
        String name=jTextField3.getText();
        String phone= jTextField4.getText();
        boolean checkSignUp=Authen.validateSignup(email, password, name, phone);
        if(checkSignUp)
        {
            AccountDTO acc = new AccountDTO(email,password,name,phone);
            boolean isCheckSignup=AccountBUS.signUp(acc);
        if(isCheckSignup)
        {
            this.setVisible(false);
            new Main().setVisible(true);
        }
    }

    } 

    private void btn_signUp1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        String email=jTextField2.getText();
        char[] pass=jTextField6.getPassword();
        String password= new String(pass);
        boolean checkLogin= Authen.validateLogin(email,password);
        if(checkLogin) {
            AccountDTO acc= new AccountDTO(email,password);
       boolean isCheck = AccountBUS.login(acc);
       if(isCheck) {
        this.setVisible(false);
        new Main().setVisible(true);
        return ;
        }
        
            JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu sai");
       
    }
    }                                        
                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_signUp;
    private javax.swing.JButton btn_signUp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPasswordField jTextField6;
    private javax.swing.JLabel label_chuaCoTK;
    private javax.swing.JLabel label_daCoTK;
    private javax.swing.JPanel login;
    private javax.swing.JPanel main_signUp;
    private javax.swing.JPanel main_signUp1;
    private javax.swing.JPanel signup;
    private javax.swing.JPanel title_signUp;
    private javax.swing.JPanel title_signUp1;
    // End of variables declaration                   
}
