/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.GUI;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;

import com.formdev.flatlaf.FlatLightLaf;
import com.project.BUS.AccountBUS;
import com.project.Common.Authen;
import com.project.DTO.AccountDTO;
import com.project.Util.Formatter;

/**
 *
 * @author thuan
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FormLogin() {
        initComponents();
        
        jTextField1.requestFocus();
        ContentSignUp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setTitle("Đăng nhập");
        ImageIcon icon = new ImageIcon("./src/assets/icon/sign-in.png");
        Image image = icon.getImage();
        Image scaledImg = image.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(scaledImg);
        setIconImage(icon.getImage());
        ContentSignUp = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ContentLogin = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        setPreferredSize(new java.awt.Dimension(535, 460));

        ContentSignUp.setMinimumSize(new java.awt.Dimension(535, 429));
        ContentSignUp.setPreferredSize(new java.awt.Dimension(535, 429));
        ContentSignUp.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đăng ký");
        jLabel5.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        jLabel5.setForeground(new Color(102, 85, 170));
        jLabel5.setPreferredSize(new java.awt.Dimension(77, 50));
        jPanel9.add(jLabel5, "card2");

        ContentSignUp.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jPanel3.setPreferredSize(new java.awt.Dimension(325, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("./src/assets/icon/login_icon_user.png")); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // jLabel6.setText("Email");
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanel3.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Formatter.setPlaceHolder(jTextField2, "Nhập email");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel3);

        jPanel11.setPreferredSize(new java.awt.Dimension(325, 50));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("./src/assets/icon/login_icon_Pwd.png"));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // jLabel7.setText("Mật khẩu");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanel11.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jPasswordField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Formatter.setPlaceHolder(jPasswordField2, "Nhập mật khẩu");
        jPanel11.add(jPasswordField2, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(325, 50));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("./src/assets/icon/login_icon_confirmPwd.png"));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanel12.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jPasswordField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Formatter.setPlaceHolder(jPasswordField3, "Nhập lại mật khẩu");
        jPanel12.add(jPasswordField3, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Đăng ký");
        Formatter.setStyleButtonLoginForm(jButton2);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel10.add(jButton2);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bạn đã có tài khoản ?");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setPreferredSize(new java.awt.Dimension(500, 30));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel8);
        jPanel10.setBackground(Color.WHITE);

        ContentSignUp.add(jPanel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContentSignUp);

        ContentLogin.setMinimumSize(new java.awt.Dimension(515, 385));
        ContentLogin.setPreferredSize(new java.awt.Dimension(515, 385));
        ContentLogin.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đăng nhập");
        jLabel3.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        jLabel3.setForeground(new Color(102, 85, 170));
        jLabel3.setPreferredSize(new java.awt.Dimension(77, 50));
        jPanel7.add(jLabel3, "card2");

        ContentLogin.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));
        jPanel5.setBackground(Color.WHITE);

        jPanel1.setPreferredSize(new java.awt.Dimension(325, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/login_icon_user.png"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // jLabel1.setText("Email");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Formatter.setPlaceHolder(jTextField1, "Nhập email");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(325, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("./src/assets/icon/login_icon_Pwd.png"));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Formatter.setPlaceHolder(jPasswordField1, "Nhập mật khẩu");
        jPanel2.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel2);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        Formatter.setStyleButtonLoginForm(jButton1);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setText("Bạn chưa có tài khoản ?");
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 30));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel4);

        ContentLogin.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContentLogin);
        Action action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ContentLogin.isVisible()) {
                    jButton1ActionPerformed(e);
                } else if (ContentSignUp.isVisible()) {
                    jButton2ActionPerformed(e);
                }
            }
        };

        ContentLogin.setFocusable(true);
        ContentLogin.setFocusable(true);

        ContentLogin.getActionMap().put("enterPressed", action);
        ContentLogin.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,
                0),
                "enterPressed");
        ContentSignUp.getActionMap().put("enterPressed", action);
        ContentSignUp.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,
                0),
                "enterPressed");

        // Vì một số lý do nào đó mà khi textfield email đang focus thì việc nhấn enter,
        // action không
        // hoạt động nên có thêm đoạn code sau

        // <------------------------------------------------------------>
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (ContentLogin.isVisible()) {
                        jButton1ActionPerformed(null);
                    } else if (ContentSignUp.isVisible()) {
                        jButton2ActionPerformed(null);
                    }
                }
            }
        });
        jTextField2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (ContentLogin.isVisible()) {
                        jButton1ActionPerformed(null);
                    } else if (ContentSignUp.isVisible()) {
                        jButton2ActionPerformed(null);
                    }
                }
            }
        });
        // <------------------------------------------------------------>

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String email = jTextField2.getText();
        String password = String.valueOf(jPasswordField2.getPassword());
        String rePassword = String.valueOf(jPasswordField3.getPassword());

        if (email.equals("") || password.equals("") || rePassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            return;
        }

        // // min length paswords
        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 6 ký tự");
            return;
        }

        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp");
            return;
        }

        // check email
        boolean check_email = Authen.validateEmail(email);

        if (check_email) {
            AccountDTO new_account = new AccountDTO(email, password);

            if (AccountBUS.createAccountBUS(new_account)) {
                JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công");
                ContentSignUp.setVisible(false);
                ContentLogin.setVisible(true);

                jTextField1.setText(email);
                jPasswordField1.setText(password);

                return;
            }

        }

    }

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {
        setTitle("Đăng nhập");
        ContentLogin.setVisible(true);
        ContentSignUp.setVisible(false);
    }

    // event click btn login
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String email = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());

        if (email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            return;
        }

        AccountDTO acc = new AccountDTO(email, password);
        if (AccountBUS.login(acc)) {
            this.setVisible(false);
            new Main().setVisible(true);
        }

    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
        setTitle("Đăng ký");
        ContentLogin.setVisible(false);
        ContentSignUp.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("PasswordField.showRevealButton", true);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel ContentLogin;
    private javax.swing.JPanel ContentSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;

    // End of variables declaration
}
