/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.GUI;

/**
 *
 * @author HP
 */
public class ProductMenu extends javax.swing.JPanel {

    /**
     * Creates new form ProductMenu
     */
    public ProductMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelSouth = new javax.swing.JPanel();
        PanelSouth1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        PanelTimkiem = new javax.swing.JPanel();
        lblMucGia = new javax.swing.JLabel();
        cmbGia = new javax.swing.JComboBox<>();
        lblSoluong = new javax.swing.JLabel();
        cmbSoluong = new javax.swing.JComboBox<>();
        lblLoaisp = new javax.swing.JLabel();
        rbtnTrs = new javax.swing.JRadioButton();
        rbtnSoda = new javax.swing.JRadioButton();
        rbtnCf = new javax.swing.JRadioButton();
        btnLoc = new javax.swing.JButton();
        PanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        PanelNorth = new javax.swing.JPanel();
        PanelSp = new javax.swing.JPanel();
        panellblSp = new javax.swing.JPanel();
        lblSanpham = new javax.swing.JLabel();
        PanelBtn = new javax.swing.JPanel();
        Btn = new javax.swing.JPanel();
        Btn1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnChitiet = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        PanellblTimkiem = new javax.swing.JPanel();
        PanellblTimkiem1 = new javax.swing.JPanel();
        btnTimkiem = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1085, 768));
        setLayout(new java.awt.BorderLayout());

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));
        PanelSouth.setMinimumSize(new java.awt.Dimension(1085, 608));
        PanelSouth.setPreferredSize(new java.awt.Dimension(1085, 600));
        PanelSouth.setLayout(new javax.swing.BoxLayout(PanelSouth, javax.swing.BoxLayout.X_AXIS));

        PanelSouth1.setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setPreferredSize(new java.awt.Dimension(600, 200));

        PanelTimkiem.setBackground(new java.awt.Color(255, 255, 255));
        PanelTimkiem.setPreferredSize(new java.awt.Dimension(200, 606));
        PanelTimkiem.setLayout(new java.awt.GridLayout(10, 1, 0, 25));

        lblMucGia.setBackground(new java.awt.Color(255, 255, 255));
        lblMucGia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblMucGia.setText("Mức giá:");
        PanelTimkiem.add(lblMucGia);

        cmbGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-15k", "15k-20k", "20k-25k", "25k-30k" }));
        cmbGia.setPreferredSize(new java.awt.Dimension(72, 15));
        PanelTimkiem.add(cmbGia);

        lblSoluong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoluong.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSoluong.setText("Số lượng bán ra:");
        PanelTimkiem.add(lblSoluong);

        cmbSoluong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Từ thấp đến cao", "Từ cao đến thấp" }));
        PanelTimkiem.add(cmbSoluong);

        lblLoaisp.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaisp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblLoaisp.setText("Loại sản phẩm: ");
        PanelTimkiem.add(lblLoaisp);

        rbtnTrs.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnTrs);
        rbtnTrs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtnTrs.setText("Trà sữa");
        PanelTimkiem.add(rbtnTrs);

        rbtnSoda.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnSoda);
        rbtnSoda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtnSoda.setText("Soda");
        PanelTimkiem.add(rbtnSoda);

        rbtnCf.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnCf);
        rbtnCf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtnCf.setSelected(true);
        rbtnCf.setText("Cà phê");
        rbtnCf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCfActionPerformed(evt);
            }
        });
        PanelTimkiem.add(rbtnCf);

        btnLoc.setBackground(new java.awt.Color(255, 255, 255));
        btnLoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLoc.setIcon(new javax.swing.ImageIcon(("src/assets/icon/filter.png"))); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelTimkiem.add(btnLoc);

        jSplitPane1.setLeftComponent(PanelTimkiem);

        PanelTable.setBackground(new java.awt.Color(255, 255, 255));
        PanelTable.setLayout(new javax.swing.BoxLayout(PanelTable, javax.swing.BoxLayout.LINE_AXIS));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HÀNG", "TÊN SẢN PHẨM", "ẢNH", "GIÁ", "", "SỐ LƯỢNG", "NGÀY", "LOẠI SẢN PHẨM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.setGridColor(new java.awt.Color(204, 204, 204));
        Table.setRowHeight(30);
        jScrollPane1.setViewportView(Table);

        PanelTable.add(jScrollPane1);

        jSplitPane1.setRightComponent(PanelTable);

        javax.swing.GroupLayout PanelSouth1Layout = new javax.swing.GroupLayout(PanelSouth1);
        PanelSouth1.setLayout(PanelSouth1Layout);
        PanelSouth1Layout.setHorizontalGroup(
            PanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
            .addGroup(PanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
        );
        PanelSouth1Layout.setVerticalGroup(
            PanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(PanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );

        PanelSouth.add(PanelSouth1);

        add(PanelSouth, java.awt.BorderLayout.CENTER);

        PanelNorth.setBackground(new java.awt.Color(255, 255, 255));
        PanelNorth.setMinimumSize(new java.awt.Dimension(1085, 160));
        PanelNorth.setPreferredSize(new java.awt.Dimension(1085, 160));
        PanelNorth.setLayout(new javax.swing.BoxLayout(PanelNorth, javax.swing.BoxLayout.Y_AXIS));

        PanelSp.setBackground(new java.awt.Color(255, 255, 255));
        PanelSp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PanelSp.setPreferredSize(new java.awt.Dimension(1085, 80));

        panellblSp.setBackground(new java.awt.Color(255, 255, 255));

        lblSanpham.setBackground(new java.awt.Color(255, 255, 255));
        lblSanpham.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        lblSanpham.setIcon(new javax.swing.ImageIcon(("src/assets/icon/icons8-product-64.png"))); // NOI18N
        lblSanpham.setText("SẢN PHẨM");
        lblSanpham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panellblSpLayout = new javax.swing.GroupLayout(panellblSp);
        panellblSp.setLayout(panellblSpLayout);
        panellblSpLayout.setHorizontalGroup(
            panellblSpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSanpham, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panellblSpLayout.setVerticalGroup(
            panellblSpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellblSpLayout.createSequentialGroup()
                .addComponent(lblSanpham)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        PanelSp.add(panellblSp);

        PanelNorth.add(PanelSp);

        PanelBtn.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtn.setPreferredSize(new java.awt.Dimension(1085, 80));
        PanelBtn.setLayout(new java.awt.BorderLayout());

        Btn.setBackground(new java.awt.Color(255, 255, 255));
        Btn.setMinimumSize(new java.awt.Dimension(410, 80));
        Btn.setPreferredSize(new java.awt.Dimension(410, 80));
        Btn.setLayout(new java.awt.BorderLayout());

        Btn1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1.setPreferredSize(new java.awt.Dimension(390, 75));
        Btn1.setLayout(new java.awt.GridLayout(1, 0));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(("src/assets/icon/plus (1).png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnThem.setBorderPainted(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setIconTextGap(10);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn1.add(btnThem);

        btnChitiet.setBackground(new java.awt.Color(255, 255, 255));
        btnChitiet.setIcon(new javax.swing.ImageIcon(("src/assets/icon/letter-i (1).png"))); // NOI18N
        btnChitiet.setText("CHI TIẾT");
        btnChitiet.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnChitiet.setBorderPainted(false);
        btnChitiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChitiet.setIconTextGap(10);
        btnChitiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn1.add(btnChitiet);

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(("src/assets/icon/remove.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnXoa.setBorderPainted(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setIconTextGap(10);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn1.add(btnXoa);

        btnXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnXuat.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnXuat.setIcon(new javax.swing.ImageIcon(("src/assets/icon/excel.png"))); // NOI18N
        btnXuat.setText("XUẤT");
        btnXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnXuat.setBorderPainted(false);
        btnXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXuat.setIconTextGap(10);
        btnXuat.setMinimumSize(new java.awt.Dimension(33, 59));
        btnXuat.setPreferredSize(new java.awt.Dimension(33, 59));
        btnXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn1.add(btnXuat);

        Btn.add(Btn1, java.awt.BorderLayout.EAST);

        PanelBtn.add(Btn, java.awt.BorderLayout.WEST);

        PanellblTimkiem.setMinimumSize(new java.awt.Dimension(685, 80));
        PanellblTimkiem.setPreferredSize(new java.awt.Dimension(675, 80));

        PanellblTimkiem1.setBackground(new java.awt.Color(255, 255, 255));
        PanellblTimkiem1.setPreferredSize(new java.awt.Dimension(600, 40));

        btnTimkiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimkiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");

        txt.setPreferredSize(new java.awt.Dimension(90, 22));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(("src/assets/icon/refresh (1).png"))); // NOI18N
        btnRefresh.setText("Làm mới");
        btnRefresh.setBorder(null);
        btnRefresh.setPreferredSize(new java.awt.Dimension(100, 41));

        javax.swing.GroupLayout PanellblTimkiem1Layout = new javax.swing.GroupLayout(PanellblTimkiem1);
        PanellblTimkiem1.setLayout(PanellblTimkiem1Layout);
        PanellblTimkiem1Layout.setHorizontalGroup(
            PanellblTimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellblTimkiem1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnTimkiem)
                .addGap(37, 37, 37)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanellblTimkiem1Layout.setVerticalGroup(
            PanellblTimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanellblTimkiem1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(PanellblTimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanellblTimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanellblTimkiemLayout = new javax.swing.GroupLayout(PanellblTimkiem);
        PanellblTimkiem.setLayout(PanellblTimkiemLayout);
        PanellblTimkiemLayout.setHorizontalGroup(
            PanellblTimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanellblTimkiemLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanellblTimkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE))
        );
        PanellblTimkiemLayout.setVerticalGroup(
            PanellblTimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanellblTimkiem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelBtn.add(PanellblTimkiem, java.awt.BorderLayout.EAST);

        PanelNorth.add(PanelBtn);

        add(PanelNorth, java.awt.BorderLayout.NORTH);
    }// </editor-fold>                        

    private void rbtnCfActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      


    // Variables declaration - do not modify                     
    private javax.swing.JPanel Btn;
    private javax.swing.JPanel Btn1;
    private javax.swing.JPanel PanelBtn;
    private javax.swing.JPanel PanelNorth;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JPanel PanelSouth1;
    private javax.swing.JPanel PanelSp;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JPanel PanelTimkiem;
    private javax.swing.JPanel PanellblTimkiem;
    private javax.swing.JPanel PanellblTimkiem1;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbGia;
    private javax.swing.JComboBox<String> cmbSoluong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblLoaisp;
    private javax.swing.JLabel lblMucGia;
    private javax.swing.JLabel lblSanpham;
    private javax.swing.JLabel lblSoluong;
    private javax.swing.JPanel panellblSp;
    private javax.swing.JRadioButton rbtnCf;
    private javax.swing.JRadioButton rbtnSoda;
    private javax.swing.JRadioButton rbtnTrs;
    private javax.swing.JTextField txt;
    // End of variables declaration                   
}






