
package com.project.GUI;

import javax.swing.JFrame;

import org.jfree.chart.*;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

class TestBarChart {

        public static ChartPanel createChart(String TitleChart) {
                JFreeChart barChart = ChartFactory.createBarChart(
                                TitleChart,
                                "Năm", "VNĐ",
                                createDataset(), PlotOrientation.VERTICAL, false, false, false);
                // Lấy Renderer của biểu đồ để thiết lập nhãn giá trị
                BarRenderer renderer = (BarRenderer) barChart.getCategoryPlot().getRenderer();
                renderer.setBaseItemLabelsVisible(true); // Cho phép hiển thị nhãn giá trị
                renderer.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator()); // Sử dụng định dạng mặc
                                                                                              // định

                // Tạo một vị trí mới để hiển thị nhãn
                ItemLabelPosition position = new ItemLabelPosition(
                                ItemLabelAnchor.OUTSIDE12,
                                TextAnchor.TOP_CENTER,
                                TextAnchor.TOP_CENTER,
                                Math.PI * 2);

                // Thiết lập vị trí cho nhãn giá trị
                renderer.setBasePositiveItemLabelPosition(position);

                ChartPanel chartPanel = new ChartPanel(barChart);
                return chartPanel;
        }

        public static CategoryDataset createDataset() {
                final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                dataset.addValue(68000000, "VNĐ", "1990");
                dataset.addValue(80000000, "VNĐ", "2000");
                dataset.addValue(88000000, "VNĐ", "2010");
                dataset.addValue(95000000, "VNĐ", "2020");
                dataset.addValue(95000000, "VNĐ", "2021");
                dataset.addValue(95000000, "VNĐ", "2022");
                dataset.addValue(95000000, "VNĐ", "2023");
                dataset.addValue(95000000, "VNĐ", "2024");
                return dataset;
        }

}

public class Statistical extends javax.swing.JPanel {

        /**
         * Creates new form Chart
         */
        public Statistical() {
                initComponents();
                TestBarChart barchartOverview = new TestBarChart();
                BoxChart.add(barchartOverview.createChart("Doanh thu theo các tháng"));
                BoxChartProduct.add(barchartOverview.createChart("Số lượng sản phẩm đã bán theo sản phẩm"));
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                TabbedPaneStatistical = new javax.swing.JTabbedPane();
                BoxOverview = new javax.swing.JPanel();
                BoxRevenue = new javax.swing.JPanel();
                IconRevenue = new javax.swing.JButton();
                TitleRevenue = new javax.swing.JLabel();
                TextRevenue = new javax.swing.JLabel();
                BoxProduct = new javax.swing.JPanel();
                IconProduct = new javax.swing.JButton();
                TitleProduct = new javax.swing.JLabel();
                TextProduct = new javax.swing.JLabel();
                BoxBill = new javax.swing.JPanel();
                IconBill = new javax.swing.JButton();
                TitleBill = new javax.swing.JLabel();
                TextBill = new javax.swing.JLabel();
                BoxChart = new javax.swing.JPanel();
                BoxStatistalProduct = new javax.swing.JPanel();
                BoxRevenueProduct = new javax.swing.JPanel();
                IconRevenue1 = new javax.swing.JButton();
                TitleRevenue1 = new javax.swing.JLabel();
                TextRevenue1 = new javax.swing.JLabel();
                TextRevenue3 = new javax.swing.JLabel();
                BoxBestSell = new javax.swing.JPanel();
                IconProduct1 = new javax.swing.JButton();
                TitleProduct1 = new javax.swing.JLabel();
                TextProduct1 = new javax.swing.JLabel();
                TextProduct3 = new javax.swing.JLabel();
                BoxLeastSell = new javax.swing.JPanel();
                IconBill1 = new javax.swing.JButton();
                TitleBill1 = new javax.swing.JLabel();
                TextBill1 = new javax.swing.JLabel();
                TextBill3 = new javax.swing.JLabel();
                BoxChartProduct = new javax.swing.JPanel();

                setMinimumSize(new java.awt.Dimension(1085, 768));
                setPreferredSize(new java.awt.Dimension(1085, 768));
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                TabbedPaneStatistical.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
                TabbedPaneStatistical.setMinimumSize(new java.awt.Dimension(1085, 768));
                TabbedPaneStatistical.setPreferredSize(new java.awt.Dimension(1085, 768));

                BoxRevenue.setBackground(new java.awt.Color(255, 255, 255));
                BoxRevenue.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                BoxRevenue.setPreferredSize(new java.awt.Dimension(300, 150));

                IconRevenue.setIcon(new javax.swing.ImageIcon("./src/assets/icon/money-64.png")); // NOI18N
                IconRevenue.setBorder(null);

                TitleRevenue.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleRevenue.setText("Tổng doanh thu");

                TextRevenue.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextRevenue.setText("10000000000");
                TextRevenue.setToolTipText("");

                javax.swing.GroupLayout BoxRevenueLayout = new javax.swing.GroupLayout(BoxRevenue);
                BoxRevenue.setLayout(BoxRevenueLayout);
                BoxRevenueLayout.setHorizontalGroup(
                                BoxRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxRevenueLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxRevenueLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(TitleRevenue,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxRevenueLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconRevenue,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(TextRevenue,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                192,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                BoxRevenueLayout.setVerticalGroup(
                                BoxRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxRevenueLayout
                                                                .createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(TitleRevenue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(BoxRevenueLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(IconRevenue,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(TextRevenue,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(32, 32, 32)));

                BoxProduct.setBackground(new java.awt.Color(255, 255, 255));
                BoxProduct.setPreferredSize(new java.awt.Dimension(300, 150));

                IconProduct.setIcon(new javax.swing.ImageIcon("./src/assets/icon/dairy-products-64.png")); // NOI18N
                IconProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

                TitleProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleProduct.setText("Tổng số sản phẩm");

                TextProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextProduct.setText("10000000000");
                TextProduct.setToolTipText("");

                javax.swing.GroupLayout BoxProductLayout = new javax.swing.GroupLayout(BoxProduct);
                BoxProduct.setLayout(BoxProductLayout);
                BoxProductLayout.setHorizontalGroup(
                                BoxProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxProductLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxProductLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(TitleProduct,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxProductLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconProduct,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(TextProduct,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                192,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                BoxProductLayout.setVerticalGroup(
                                BoxProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxProductLayout
                                                                .createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(TitleProduct,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(BoxProductLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(IconProduct,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(TextProduct,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(32, 32, 32)));

                BoxBill.setBackground(new java.awt.Color(255, 255, 255));
                BoxBill.setPreferredSize(new java.awt.Dimension(300, 150));

                IconBill.setIcon(new javax.swing.ImageIcon("./src/assets/icon/bill-64.png")); // NOI18N
                IconBill.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

                TitleBill.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleBill.setText("Tổng số đơn hàng");

                TextBill.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextBill.setText("12");
                TextBill.setToolTipText("");
                TextBill.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                javax.swing.GroupLayout BoxBillLayout = new javax.swing.GroupLayout(BoxBill);
                BoxBill.setLayout(BoxBillLayout);
                BoxBillLayout.setHorizontalGroup(
                                BoxBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxBillLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxBillLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(TitleBill,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                288,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxBillLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconBill,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(TextBill,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                BoxBillLayout.setVerticalGroup(
                                BoxBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxBillLayout
                                                                .createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(TitleBill,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                24,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(BoxBillLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(IconBill,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(TextBill,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(32, 32, 32)));

                BoxChart.setBackground(new java.awt.Color(255, 255, 255));
                BoxChart.setLayout(new javax.swing.BoxLayout(BoxChart, javax.swing.BoxLayout.LINE_AXIS));

                javax.swing.GroupLayout BoxOverviewLayout = new javax.swing.GroupLayout(BoxOverview);
                BoxOverview.setLayout(BoxOverviewLayout);
                BoxOverviewLayout.setHorizontalGroup(
                                BoxOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxOverviewLayout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(BoxRevenue,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(BoxProduct,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(BoxBill,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxOverviewLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(BoxChart,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                BoxOverviewLayout.setVerticalGroup(
                                BoxOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxOverviewLayout.createSequentialGroup()
                                                                .addGap(56, 56, 56)
                                                                .addGroup(
                                                                                BoxOverviewLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(BoxBill,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(BoxProduct,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(BoxRevenue,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(36, 36, 36)
                                                                .addComponent(BoxChart,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                TabbedPaneStatistical.addTab("Tổng quan", BoxOverview);

                BoxRevenueProduct.setBackground(new java.awt.Color(255, 255, 255));
                BoxRevenueProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                BoxRevenueProduct.setPreferredSize(new java.awt.Dimension(300, 150));

                IconRevenue1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/revenue-64.png")); // NOI18N
                IconRevenue1.setBorder(null);

                TitleRevenue1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleRevenue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleRevenue1.setText("sản phẩm doanh thu cao nhất");

                TextRevenue1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextRevenue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextRevenue1.setText("tên sản phẩm");
                TextRevenue1.setToolTipText("");

                TextRevenue3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextRevenue3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextRevenue3.setText("giá");
                TextRevenue3.setToolTipText("");

                javax.swing.GroupLayout BoxRevenueProductLayout = new javax.swing.GroupLayout(BoxRevenueProduct);
                BoxRevenueProduct.setLayout(BoxRevenueProductLayout);
                BoxRevenueProductLayout.setHorizontalGroup(
                                BoxRevenueProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxRevenueProductLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxRevenueProductLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(TitleRevenue1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxRevenueProductLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconRevenue1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(BoxRevenueProductLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(TextRevenue1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                192,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(TextRevenue3,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                192,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addContainerGap()));
                BoxRevenueProductLayout.setVerticalGroup(
                                BoxRevenueProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                BoxRevenueProductLayout
                                                                                .createSequentialGroup()
                                                                                .addGap(12, 12, 12)
                                                                                .addComponent(TitleRevenue1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(BoxRevenueProductLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(IconRevenue1)
                                                                                                .addGroup(BoxRevenueProductLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(TextRevenue1)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(TextRevenue3)))
                                                                                .addGap(32, 32, 32)));

                BoxBestSell.setBackground(new java.awt.Color(255, 255, 255));
                BoxBestSell.setPreferredSize(new java.awt.Dimension(300, 150));

                IconProduct1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/best-product-64.png")); // NOI18N
                IconProduct1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

                TitleProduct1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleProduct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleProduct1.setText("Sản phẩm bán chạy nhất");

                TextProduct1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextProduct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextProduct1.setText("tên sản phẩm");
                TextProduct1.setToolTipText("");

                TextProduct3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextProduct3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextProduct3.setText("giá");
                TextProduct3.setToolTipText("");

                javax.swing.GroupLayout BoxBestSellLayout = new javax.swing.GroupLayout(BoxBestSell);
                BoxBestSell.setLayout(BoxBestSellLayout);
                BoxBestSellLayout.setHorizontalGroup(
                                BoxBestSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxBestSellLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxBestSellLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(TitleProduct1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxBestSellLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconProduct1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(BoxBestSellLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(TextProduct1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                192,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(TextProduct3,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                192,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addContainerGap()));
                BoxBestSellLayout.setVerticalGroup(
                                BoxBestSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxBestSellLayout
                                                                .createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(TitleProduct1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(BoxBestSellLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(IconProduct1)
                                                                                .addGroup(BoxBestSellLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(TextProduct1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(TextProduct3)))
                                                                .addGap(32, 32, 32)));

                BoxLeastSell.setBackground(new java.awt.Color(255, 255, 255));
                BoxLeastSell.setPreferredSize(new java.awt.Dimension(300, 150));

                IconBill1.setIcon(new javax.swing.ImageIcon("./src/assets/icon/disadvantage-64.png")); // NOI18N
                IconBill1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

                TitleBill1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TitleBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TitleBill1.setText("Sản phẩm bán ít nhất");

                TextBill1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextBill1.setText("tên sản phẩm");
                TextBill1.setToolTipText("");
                TextBill1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                TextBill3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                TextBill3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TextBill3.setText("giá");
                TextBill3.setToolTipText("");
                TextBill3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                javax.swing.GroupLayout BoxLeastSellLayout = new javax.swing.GroupLayout(BoxLeastSell);
                BoxLeastSell.setLayout(BoxLeastSellLayout);
                BoxLeastSellLayout.setHorizontalGroup(
                                BoxLeastSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxLeastSellLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxLeastSellLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(TitleBill1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                288,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(BoxLeastSellLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IconBill1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                90,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(BoxLeastSellLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(TextBill1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(TextBill3,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addContainerGap()));
                BoxLeastSellLayout.setVerticalGroup(
                                BoxLeastSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxLeastSellLayout
                                                                .createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(TitleBill1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                24,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(BoxLeastSellLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(IconBill1)
                                                                                .addGroup(BoxLeastSellLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(TextBill1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(TextBill3)))
                                                                .addContainerGap(30, Short.MAX_VALUE)));

                BoxChartProduct.setBackground(new java.awt.Color(255, 255, 255));
                BoxChartProduct.setLayout(new javax.swing.BoxLayout(BoxChartProduct, javax.swing.BoxLayout.LINE_AXIS));

                javax.swing.GroupLayout BoxStatistalProductLayout = new javax.swing.GroupLayout(BoxStatistalProduct);
                BoxStatistalProduct.setLayout(BoxStatistalProductLayout);
                BoxStatistalProductLayout.setHorizontalGroup(
                                BoxStatistalProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxStatistalProductLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(BoxStatistalProductLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(BoxStatistalProductLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(BoxRevenueProduct,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(BoxBestSell,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(BoxLeastSell,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addComponent(BoxChartProduct,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                BoxStatistalProductLayout.setVerticalGroup(
                                BoxStatistalProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxStatistalProductLayout.createSequentialGroup()
                                                                .addGap(56, 56, 56)
                                                                .addGroup(BoxStatistalProductLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(BoxLeastSell,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(BoxBestSell,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(BoxRevenueProduct,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(36, 36, 36)
                                                                .addComponent(BoxChartProduct,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                TabbedPaneStatistical.addTab("Sản phẩm", BoxStatistalProduct);

                add(TabbedPaneStatistical);
        }// </editor-fold>

        // Variables declaration - do not modify
        private javax.swing.JPanel BoxBestSell;
        private javax.swing.JPanel BoxBill;
        private javax.swing.JPanel BoxChart;
        private javax.swing.JPanel BoxChartProduct;
        private javax.swing.JPanel BoxLeastSell;
        private javax.swing.JPanel BoxOverview;
        private javax.swing.JPanel BoxProduct;
        private javax.swing.JPanel BoxRevenue;
        private javax.swing.JPanel BoxRevenueProduct;
        private javax.swing.JPanel BoxStatistalProduct;
        private javax.swing.JButton IconBill;
        private javax.swing.JButton IconBill1;
        private javax.swing.JButton IconProduct;
        private javax.swing.JButton IconProduct1;
        private javax.swing.JButton IconRevenue;
        private javax.swing.JButton IconRevenue1;
        private javax.swing.JTabbedPane TabbedPaneStatistical;
        private javax.swing.JLabel TextBill;
        private javax.swing.JLabel TextBill1;
        private javax.swing.JLabel TextBill3;
        private javax.swing.JLabel TextProduct;
        private javax.swing.JLabel TextProduct1;
        private javax.swing.JLabel TextProduct3;
        private javax.swing.JLabel TextRevenue;
        private javax.swing.JLabel TextRevenue1;
        private javax.swing.JLabel TextRevenue3;
        private javax.swing.JLabel TitleBill;
        private javax.swing.JLabel TitleBill1;
        private javax.swing.JLabel TitleProduct;
        private javax.swing.JLabel TitleProduct1;
        private javax.swing.JLabel TitleRevenue;
        private javax.swing.JLabel TitleRevenue1;
        // End of variables declaration
}
