package com.project.GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author thuan
 */
public class Supplier extends javax.swing.JPanel {

        /**
         * Creates new form Supplier
         */
        public Supplier() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                SupplierTop = new javax.swing.JPanel();
                BoxBtn = new javax.swing.JPanel();
                BtnAdd = new javax.swing.JButton();
                BtnDetail = new javax.swing.JButton();
                BtnDelete = new javax.swing.JButton();
                BtnImportExcel = new javax.swing.JButton();
                BtnExportExcel = new javax.swing.JButton();
                BoxSearch = new javax.swing.JPanel();
                SearchTextField = new javax.swing.JTextField();
                Filter = new javax.swing.JComboBox<>();
                BtnRefresh = new javax.swing.JButton();
                SupplierCenter = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                TableSupplier = new javax.swing.JTable();

                setMinimumSize(new java.awt.Dimension(1085, 768));
                setName(""); // NOI18N
                setPreferredSize(new java.awt.Dimension(1085, 768));
                setLayout(new java.awt.BorderLayout(0, 5));

                SupplierTop.setBackground(new java.awt.Color(255, 255, 255));
                SupplierTop.setPreferredSize(new java.awt.Dimension(608, 100));

                BoxBtn.setBackground(new java.awt.Color(255, 255, 255));
                BoxBtn.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

                BtnAdd.setBackground(new java.awt.Color(248, 249, 250));
                BtnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnAdd.setIcon(new javax.swing.ImageIcon("./src/assets/icon/plus.png")); // NOI18N
                BtnAdd.setText("Thêm");
                BtnAdd.setBorder(null);
                BtnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BtnAdd.setIconTextGap(8);
                BtnAdd.setMaximumSize(new java.awt.Dimension(80, 80));
                BtnAdd.setMinimumSize(new java.awt.Dimension(80, 80));
                BtnAdd.setPreferredSize(new java.awt.Dimension(80, 80));
                BtnAdd.setVerifyInputWhenFocusTarget(false);
                BtnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                BtnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnAddActionPerformed(evt);
                        }
                });
                BoxBtn.add(BtnAdd);

                BtnDetail.setBackground(new java.awt.Color(248, 249, 250));
                BtnDetail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnDetail.setIcon(new javax.swing.ImageIcon("./src/assets/icon/info-rgb.png")); // NOI18N
                BtnDetail.setText("Chi tiết");
                BtnDetail.setBorder(null);
                BtnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BtnDetail.setIconTextGap(8);
                BtnDetail.setMaximumSize(new java.awt.Dimension(80, 80));
                BtnDetail.setMinimumSize(new java.awt.Dimension(80, 80));
                BtnDetail.setPreferredSize(new java.awt.Dimension(80, 80));
                BtnDetail.setVerifyInputWhenFocusTarget(false);
                BtnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                BtnDetail.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnDetailActionPerformed(evt);
                        }
                });
                BoxBtn.add(BtnDetail);

                BtnDelete.setBackground(new java.awt.Color(248, 249, 250));
                BtnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnDelete.setIcon(new javax.swing.ImageIcon("./src/assets/icon/cancel.png")); // NOI18N
                BtnDelete.setText("Xoá");
                BtnDelete.setBorder(null);
                BtnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BtnDelete.setIconTextGap(8);
                BtnDelete.setMaximumSize(new java.awt.Dimension(80, 80));
                BtnDelete.setMinimumSize(new java.awt.Dimension(80, 80));
                BtnDelete.setPreferredSize(new java.awt.Dimension(80, 80));
                BtnDelete.setVerifyInputWhenFocusTarget(false);
                BtnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                BtnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnDeleteActionPerformed(evt);
                        }
                });
                BoxBtn.add(BtnDelete);

                BtnImportExcel.setBackground(new java.awt.Color(248, 249, 250));
                BtnImportExcel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnImportExcel.setIcon(new javax.swing.ImageIcon("./src/assets/icon/upload-file.png")); // NOI18N
                BtnImportExcel.setText("Nhập excel");
                BtnImportExcel.setBorder(null);
                BtnImportExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BtnImportExcel.setIconTextGap(8);
                BtnImportExcel.setMaximumSize(new java.awt.Dimension(80, 80));
                BtnImportExcel.setMinimumSize(new java.awt.Dimension(80, 80));
                BtnImportExcel.setPreferredSize(new java.awt.Dimension(80, 80));
                BtnImportExcel.setVerifyInputWhenFocusTarget(false);
                BtnImportExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                BtnImportExcel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnImportExcelActionPerformed(evt);
                        }
                });
                BoxBtn.add(BtnImportExcel);

                BtnExportExcel.setBackground(new java.awt.Color(248, 249, 250));
                BtnExportExcel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnExportExcel.setIcon(new javax.swing.ImageIcon("./src/assets/icon/xls.png")); // NOI18N
                BtnExportExcel.setText("Xuất excel");
                BtnExportExcel.setBorder(null);
                BtnExportExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BtnExportExcel.setIconTextGap(8);
                BtnExportExcel.setMaximumSize(new java.awt.Dimension(80, 80));
                BtnExportExcel.setMinimumSize(new java.awt.Dimension(80, 80));
                BtnExportExcel.setPreferredSize(new java.awt.Dimension(80, 80));
                BtnExportExcel.setVerifyInputWhenFocusTarget(false);
                BtnExportExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                BtnExportExcel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnExportExcelActionPerformed(evt);
                        }
                });
                BoxBtn.add(BtnExportExcel);

                BoxSearch.setBackground(new java.awt.Color(255, 255, 255));

                SearchTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                SearchTextField.setText("Tìm kiếm ....");
                SearchTextField.setKeymap(null);
                SearchTextField.setMargin(new java.awt.Insets(2, 10, 2, 6));

                Filter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                Filter.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                Filter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                BtnRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                BtnRefresh.setIcon(new javax.swing.ImageIcon("./src/assets/icon/refresh.png")); // NOI18N
                BtnRefresh.setText("Làm mới");

                javax.swing.GroupLayout BoxSearchLayout = new javax.swing.GroupLayout(BoxSearch);
                BoxSearch.setLayout(BoxSearchLayout);
                BoxSearchLayout.setHorizontalGroup(
                                BoxSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxSearchLayout
                                                                .createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(Filter,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(SearchTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                281,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                36,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(BtnRefresh)));
                BoxSearchLayout.setVerticalGroup(
                                BoxSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BoxSearchLayout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addGroup(
                                                                                BoxSearchLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(SearchTextField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                55,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(Filter,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                55,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(BtnRefresh,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                55,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout SupplierTopLayout = new javax.swing.GroupLayout(SupplierTop);
                SupplierTop.setLayout(SupplierTopLayout);
                SupplierTopLayout.setHorizontalGroup(
                                SupplierTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(SupplierTopLayout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(BoxBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(BoxSearch,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21)));
                SupplierTopLayout.setVerticalGroup(
                                SupplierTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupplierTopLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(SupplierTopLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(SupplierTopLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 8, Short.MAX_VALUE)
                                                                                                .addComponent(BoxBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(BoxSearch,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));

                add(SupplierTop, java.awt.BorderLayout.PAGE_START);

                SupplierCenter.setLayout(new javax.swing.BoxLayout(SupplierCenter, javax.swing.BoxLayout.LINE_AXIS));

                TableSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                TableSupplier.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { "test", "test", "test", "test", "test", "test" },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null }
                                },
                                new String[] {
                                                "ID", "Tên nhà cung cấp", "Địa chỉ", "Điện thoại", "Email", "Ngày tạo",
                                                "Cập nhật cuối"
                                }));
                TableSupplier.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(TableSupplier);

                SupplierCenter.add(jScrollPane1);

                add(SupplierCenter, java.awt.BorderLayout.CENTER);
        }// </editor-fold>

        private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {
                new FormSupplier("Thêm nhà cung cấp").setVisible(true);
        }

        private void BtnDetailActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = TableSupplier.getSelectedRow();
                if (selectedRow != -1) {
                        Object value1 = TableSupplier.getValueAt(selectedRow, 0);
                        Object value2 = TableSupplier.getValueAt(selectedRow, 1);
                        Object value3 = TableSupplier.getValueAt(selectedRow, 2);
                        System.out.println(value1);
                        System.out.println(value2);
                        System.out.println(value3);

                        new FormSupplier("Chi tiết nhà cung cấp").setVisible(true);
                }
        }

        private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void BtnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void BtnImportExcelActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        // Variables declaration - do not modify
        private javax.swing.JPanel BoxBtn;
        private javax.swing.JPanel BoxSearch;
        private javax.swing.JButton BtnAdd;
        private javax.swing.JButton BtnDelete;
        private javax.swing.JButton BtnDetail;
        private javax.swing.JButton BtnExportExcel;
        private javax.swing.JButton BtnImportExcel;
        private javax.swing.JButton BtnRefresh;
        private javax.swing.JComboBox<String> Filter;
        private javax.swing.JTextField SearchTextField;
        private javax.swing.JPanel SupplierCenter;
        private javax.swing.JPanel SupplierTop;
        private javax.swing.JTable TableSupplier;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration
}
